apiVersion: 0.0.1
provider: "bitbucket"
repoURL: "https://bitbucket.org/intoto-dev/intoto-apparatus-v3"
filter:
  - fix
  - feat
  - BREAKING CHANGE
  - build
  - chore
  - ci
  - docs
  - style
  - refactor
  - perf
  - test

