apiVersion: 0.0.1
repoURL: "https://bitbucket.org/intoto-dev/intoto-apparatus-v3"
commitPath: "/commits"
comparePath: "/branches/compare"

filter:
  - fix
  - feat
  - BREAKING CHANGE
  - build
  - chore
  - ci
  - docs
  - style
  - refactor
  - perf
  - test

